[package]
name = "word_morph"
version = "0.1.0"
authors = ["Srikanth <srikanth.mahesh1234@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enchant = "0.2.0"
read_input = "0.8"

